# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O_KiP9Q19VRQW8_fSVcprgqq_AW2Mib1
"""

a="привет1466"
b=5.5
c=int(input())
print(b+c)

a=5
b=6
b=a
print(a+b)

a=5
b=int(input())
print(a*b)

a=int(input())
b=int(input())
c=a+b
print(c**2)

a=15
b=10
p=a+b
C=int(input())
print(p/C)

a=int(input())
b=int(input())
print(a**2+2*a*b+b**2)

a=int(input())
b=int(input())
c=int(input())
P=a+b+c
n=P/2
S=((n-a)*(n-b)*(n-c)*n)**0.5
print(P,S)

a=int(input())
b=int(input())
print(((a**3+14)/5)*b)

a=int(input())
n=int(input())
print((a**2)//n)

a=int(input())
b=int(input())
w=float(input())
x=float(input())
c=w//x
n=a*b
m=a%b
print(c,n,m)

n=int(input())
d=n//86400
h=(n%86400)//3600
m=((n%86400)%3600)//60
print(d,h,m)

n=int(input())
S=n+n*11+n*111
print(S)